# Generated by Django 4.1.5 on 2023-03-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_alter_enrollment_price_alter_membershipplan_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
